version: "3.8"

services:
  web:
    container_name: "web"
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/opt/app

  api:
    container_name: "api"
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/opt/app

  nginx:
    container_name: "mynginx"
    image: nginx:1.25.3-alpine3.18
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./static:/opt/app/static
    depends_on:
      - web
